Create ray cluster and make ray job kubeRay compatible
michelangelo-ai/michelangelo pull request #21
Opened 2024-12-18 01:14 UTC by badcount

1. Create new ray cluster, 
2. Modify existing ray job for job-only specs, 
3. Referring cluster in RayJob for association

2024-12-18 21:37 UTC, mincai requested changes

2024-12-18 21:37 UTC, mincai commented on proto/api/v2/ray_job.proto
> +  string entrypoint = 3;
Detailed comments ?

2024-12-18 21:37 UTC, mincai commented on proto/api/v2/ray_job.proto
> +  RAY_JOB_V2_STATE_INVALID = 0;
Why do we need `RAY_JOB_V2_XXX` instead of just `RAY_JOB_XXX` ?

2024-12-18 21:37 UTC, mincai commented on proto/api/v2/ray_job.proto
> +message RayJobV2Status {
Please add detailed comments for each fields in the proto definition.

2024-12-18 21:41 UTC, badcount commented on proto/api/v2/ray_job.proto
> +  string entrypoint = 3;
Added

2024-12-18 21:56 UTC, badcount commented on proto/api/v2/ray_job.proto
> +  RAY_JOB_V2_STATE_INVALID = 0;
Good catch, updated

2024-12-19 00:40 UTC, mincai commented on proto/api/v2/ray_cluster.proto
> +  double object_store_memory_ratio = 5;
this is for the entrypoint param

2024-12-19 00:40 UTC, mincai commented on proto/api/v2/ray_cluster.proto
> +  // Endpoint for client communication with the Ray cluster
can you provide an example in the comment ? Is endpoint a name or URL ?

2024-12-19 00:40 UTC, mincai commented on proto/api/v2/ray_cluster.proto
> +  bool enable_in_tree_autoscaling = 6;
Do we need this ? What's the corresponding field in KubeRay CRD ?

2024-12-19 00:40 UTC, mincai commented on proto/api/v2/ray_job.proto
> +  // Deployment status of the Ray job
Can we provide some examples of possible status ?

2024-12-19 01:23 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  bool enable_in_tree_autoscaling = 6;
Removed

2024-12-19 02:16 UTC, badcount commented on proto/api/v2/ray_job.proto
> +  // Deployment status of the Ray job
Updated

2024-12-19 02:25 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  double object_store_memory_ratio = 5;
updated

2024-12-19 16:24 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  // Endpoint for client communication with the Ray cluster
Provided examples for each Endponits

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  // Kubernetes service type for the head service
I don't think there's any plan for us to use this because of our networking stack. If we cannot use or test it, I'd vote to remove it.

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  PodSpec pod = 2;
do we plan to change these to v1 native types?

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  double object_store_memory_ratio = 5;
hi, @badcount is the update made already? I don't see any change.

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  RAY_CLUSTER_STATE_PROVISIONING = 2;
what's the difference b/w these two?

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +
There's an overlap b/w this message and the Endpoints message.

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  // Desired number of worker replicas across all groups.
why are these part of the status? Shouldn't these instead be in the spec?

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  k8s.io.apimachinery.pkg.apis.meta.v1.Time last_update_time = 9;
are we sure we can support this? Do we want to be consistent with other CRDs where we're not using this because of serialization issues?

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  k8s.io.apimachinery.pkg.apis.meta.v1.Time last_update_time = 9;
@ying-zheng FYI ^

2024-12-20 04:59 UTC, bhjoshi1 commented on proto/api/v2/ray_job.proto
> +  map<string, string> ray_conf = 2;
should this be present in both cluster and job CRDs?

2024-12-20 05:02 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  double object_store_memory_ratio = 5;
I don't think this can be updated automatically, you can check the file here: https://github.com/michelangelo-ai/michelangelo/pull/21/files

2024-12-20 05:05 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  // Kubernetes service type for the head service
Yes, we can use it as head node spec, that's very similar to kuberay head spec anyway: https://github.com/ray-project/kuberay/blob/master/ray-operator/apis/ray/v1/raycluster_types.go#L42

2024-12-20 05:05 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  PodSpec pod = 2;
Yes, we do, this is just for now to unblock. Once Ying get the proto ready, we will use native v1 proto

2024-12-20 05:06 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  RAY_CLUSTER_STATE_PROVISIONING = 2;
creating is to create the cluster, and then we go to provisioning state for the pod to get ready, this need to be a two seprate state so we avoid to create the cluster again.

2024-12-20 05:07 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  // Desired number of worker replicas across all groups.
Kuberay returns the available worker in the status.
https://github.com/ray-project/kuberay/blob/master/ray-operator/apis/ray/v1/raycluster_types.go#L169

2024-12-20 05:11 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +
Agree, removed and use HeadnoteInfo instead

2024-12-20 05:14 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  k8s.io.apimachinery.pkg.apis.meta.v1.Time last_update_time = 9;
This returned from KubeRay, i added this for updated time just nice to have it.

2024-12-20 05:16 UTC, badcount commented on proto/api/v2/ray_job.proto
> +  map<string, string> ray_conf = 2;
Good call, removed it.

2024-12-20 18:13 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  RAY_CLUSTER_STATE_PROVISIONING = 2;
What is creating conveying? Creating the CRD?

2024-12-20 18:15 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  RAY_CLUSTER_STATE_PROVISIONING = 2;
Yes, it creates the ray.io/RayCluster CRD

2024-12-20 18:19 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  // Kubernetes service type for the head service
How will we test any code based on this?

2024-12-20 18:24 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  double object_store_memory_ratio = 5;
I see the update to the comment. What I mean to say is that this should not be present here at all since it is part of the entrypoint.

2024-12-20 18:26 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  RAY_CLUSTER_STATE_PROVISIONING = 2;
Then should it be called LAUNCHED instead? CREATING is a one shot operation. It's not a long running operation.

2024-12-20 18:28 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  // Desired number of worker replicas across all groups.
I don't think having the same field on both spec and status is correct. Our operator does not need to set it.

2024-12-20 18:30 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  // Unique identifier for the generated Ray cluster in the Ray operator.
why do we need this? namespace + name should be the unique identifier right?

2024-12-20 18:32 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  k8s.io.apimachinery.pkg.apis.meta.v1.Time last_update_time = 9;
I understand. But we cannot serialize it in our protobuf.

2024-12-20 19:26 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  // Kubernetes service type for the head service
this is not final version, we can continue iterate this on the apiserver and controllerMgr.

2024-12-20 19:27 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  double object_store_memory_ratio = 5;
Got it, moved it to the RayJob

2024-12-20 19:28 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  RAY_CLUSTER_STATE_PROVISIONING = 2;
Creating is just shot one indeed, the long one is "provisoning". I updated to launched.

2024-12-20 19:30 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  // Desired number of worker replicas across all groups.
This is kuberay standard, any reason why we don't need this?

2024-12-20 19:34 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  // Unique identifier for the generated Ray cluster in the Ray operator.
removed.

2024-12-21 01:34 UTC, bhjoshi1 commented on proto/api/v2/ray_cluster.proto
> +  // Desired number of worker replicas across all groups.
Because these are part of the spec. Repeating them in the status looks incorrect to me. As part of the input, we specify a min and a max number of replicas. The CRD can tell us the current number of replicas in the status. But why does it need to repeat desired, min and max in the status?

2024-12-21 01:37 UTC, bhjoshi1 commented on proto/api/v2/ray_job.proto
> +  string ray_cluster_status = 5;
why does the job have the status of the cluster? We should refer to the cluster and get the status from the cluster CRD. Otherwise, there will be an issues of keeping them in sync.

2024-12-21 01:38 UTC, bhjoshi1 commented on proto/api/v2/ray_job.proto
> +  //   - "Error: <specific_error>": A custom error message, such as "Error: Insufficient Memory".
should this be an enum instead?

2024-12-21 01:42 UTC, bhjoshi1 commented on proto/api/v2/ray_job.proto
> +  // URL to access the Ray job's dashboard
This will be a property of the cluster. It doesn't depend on the job.

2024-12-21 02:10 UTC, badcount commented on proto/api/v2/ray_job.proto
> +  // URL to access the Ray job's dashboard
I just checked, somehow cluster endpoint return the port only, but the job status return full url like:
status:
  dashboardURL: rc-uf-ray-h24lq-lkgzw-head-svc.default.svc.cluster.local:8265
  endTime: "2024-12-21T01:29:00Z"
  failed: 0
  jobDeploymentStatus: Complete
  jobId: ray-uf-rj-uf-ray-h24lq-7tqsm-sxwlx
  jobStatus: SUCCEEDED
  message: Job finished successfully.
  rayClusterName: rc-uf-ray-h24lq-lkgzw
  rayClusterStatus:
    availableWorkerReplicas: 1
    desiredCPU: "2"
    desiredGPU: "0"
    desiredMemory: 2Gi
    desiredTPU: "0"
    desiredWorkerReplicas: 1
    endpoints:
      client: "10001"
      dashboard: "8265"
      metrics: "8080"
      redis: "6379"
      serve: "8000"
    head:
      podIP: 10.244.0.39
      podName: rc-uf-ray-h24lq-lkgzw-head-qqdkn
      serviceIP: 10.244.0.39
      serviceName: rc-uf-ray-h24lq-lkgzw-head-svc
    lastUpdateTime: "2024-12-21T01:28:31Z"
    maxWorkerReplicas: 1
    minWorkerReplicas: 1
    observedGeneration: 1
    readyWorkerReplicas: 1
    state: ready
    stateTransitionTimes:
      ready: "2024-12-21T01:28:31Z"
  startTime: "2024-12-21T01:28:51Z"
  succeeded: 1

2024-12-21 02:11 UTC, badcount commented on proto/api/v2/ray_job.proto
> +  //   - "Error: <specific_error>": A custom error message, such as "Error: Insufficient Memory".
I think it's better to keep it as string before once we change version, we don't have to update this status

2024-12-21 02:11 UTC, badcount commented on proto/api/v2/ray_cluster.proto
> +  // Desired number of worker replicas across all groups.
I don't know, i guess there could be reason in KubeRay side? But I think this is not a blocker, remove this for now

2024-12-21 02:13 UTC, badcount commented on proto/api/v2/ray_job.proto
> +  string ray_cluster_status = 5;
removed it for now, will add it later if we find out we need it. Again, this is all from existing rayJob status

2024-12-23 19:47 UTC, sallycr approved these changes
Min Cai
I am OOTO today. You can ask him to merge first
Min Cai
I will do a post commit review later

2024-12-23 19:47 UTC, sallycr commented on proto/api/v2/ray_job.proto
> +  string jobDeploymentStatus = 7;
I see that mixed use of snake case vs carmel case. Is this mistakenly used? can we go with snake case as consistently?

2024-12-23 19:47 UTC, sallycr commented on proto/api/v2/ray_job.proto
> +  string jobId = 4;
@badcount Do we have job id in job spec?

2024-12-23 20:06 UTC, merged